### ISSUE TITLE
Fails to compile on GHC8.8.x

### ISSUE THREAD

**Issue by luc-tielen** [sol/hpack#370]
I am getting a compile error when building with GHC8.8.1 (MonadFail proposal is finally finished, removing it from Monad).

```
...
Building test suite 'spec' for hpack-0.32.0..
[ 1 of 46] Compiling Data.Aeson.Config.Parser ( src/Data/Aeson/Config/Parser.hs, dist/build/spec/spec-tmp/Data/Aeson/Config/Parser.o )

src/Data/Aeson/Config/Parser.hs:116:14: error:
    • No instance for (MonadFail Parser) arising from a use of ‘fail’
      There are instances for similar types:
        instance MonadFail Aeson.Parser
          -- Defined in ‘aeson-1.4.4.0:Data.Aeson.Types.Internal’
    • In the expression: fail $ "key " ++ show key ++ " not present"
      In a case alternative:
          Nothing -> fail $ "key " ++ show key ++ " not present"
      In the expression:
        case HashMap.lookup key o of
          Nothing -> fail $ "key " ++ show key ++ " not present"
          Just v -> p v <?> Aeson.Key key
    |
116 |   Nothing -> fail $ "key " ++ show key ++ " not present"
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

I think the fix is to derive `MonadFail` as well at https://github.com/sol/hpack/blob/master/src/Data/Aeson/Config/Parser.hs#L64 

EDIT: I just saw #369 was already opened, so I will close this comment.
